- name: "[{{ name }}] deploy"
  block:
    - name: "[{{ name }}] deploy service"
      community.docker.docker_swarm_service:
        name: "{{ name }}"
        image: "rabbitmq:3-management"
        state: present
        networks:
          - name: "{{ networkName }}"
        env:
          - RABBITMQ_DEFAULT_USER={{ rmq.user }}
          - RABBITMQ_DEFAULT_PASS={{ rmq.password }}
  tags: "{{ name }}"


