---
- name: Create network
  community.docker.docker_network:
    name: "{{ networkName }}"
    driver: overlay

- name: deploy services
  ansible.builtin.include_tasks:
    file: "../services/{{ item }}/service.yml"
    apply:
      tags: "{{ item }}"
  vars:
    - name: "{{ item.name }}"
    - version: "{{ item.version }}"
  loop: "{{ services }}"
