---
- name: Create network
  community.docker.docker_network:
    name: "{{ networkName }}"
    driver: overlay

- name: deploy services
  ansible.builtin.include_tasks: "../services/{{ item }}/service.yml"
  vars:
    - name: "{{ item }}"
  loop: "{{ services }}"
