---
- name: "[{{ name }}] Config secret"
  ansible.builtin.include_tasks:
    file: "../secret.yml"


- name: "[{{ name }}] deploy"
  block:
  - name: "[{{ name }}] deploy service"
    community.docker.docker_swarm_service:
      name: "{{ name }}"
      image: localhost:5000/api:latest
      state: present
      networks:
        - name: "{{ networkName }}"
      publish:
        - mode: ingress
          protocol: tcp
          published_port: 3002
          target_port: 3000
      secrets:
        - secret_name: "{{name}}.env"
          filename: /opt/app/.env


