galaxy_info:
  role_name: preconfig
  description: Set up docker in servers
  author: Vladislav Saliy
  license: MIT
  min_ansible_version: 2.9
  platforms: 
    - name: Ubuntu
      versions:
        - all
