---
- name: Init a new swarm with default parameters
  community.docker.docker_swarm:
    state: present
    advertise_addr: "{{ advertise_addr }}"
  register: token

- name: make token dir
  local_action:
    module: file
    path: "./tokens"
    state: directory

- name: save manager token
  local_action:
    module: copy
    dest: ./tokens/token-manager
    content: "{{ token.swarm_facts.JoinTokens.Manager }}"

- name: save worker token
  local_action:
    module: copy
    dest: ./tokens/token-worker
    content: "{{ token.swarm_facts.JoinTokens.Worker }}"



